// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto_Common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HHFramework.Proto {

  /// <summary>Holder for reflection information generated from Proto_Common.proto</summary>
  public static partial class ProtoCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto_Common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJQcm90b19Db21tb24ucHJvdG8SEUhIRnJhbWV3b3JrLlByb3RvIioKB1Zl",
            "Y3RvcjMSCQoBeBgBIAEoAhIJCgF5GAIgASgCEgkKAXoYAyABKAIqIwoIUm9s",
            "ZVR5cGUSCgoGUGxheWVyEAASCwoHTW9uc3RlchABKi4KC09mZmxpbmVUeXBl",
            "EhIKDlNlcnZlck1haW50YWluEAASCwoHUmVwbGFjZRABKikKEkxlYXZlU2Nl",
            "bmVMaW5lVHlwZRIKCgZOb3JtYWwQABIHCgNEaWUQASpVChBQbGF5ZXJBY3Rp",
            "b25UeXBlEg0KCUNsaWNrTW92ZRAAEg4KClNlcnZlck1vdmUQARIQCgxKb3lz",
            "dGlja01vdmUQAhIQCgxKb3lzdGlja1N0b3AQAyovChFSb2xlQmF0dGxlUmV0",
            "Q29kZRIICgROb25lEAASEAoMTXBEZWZpY2llbmN5EAEqTQoLQ2hhdENoYW5u",
            "ZWwSBwoDU3lzEAASCQoFV29ybGQQARIKCgZGcmllbmQQAhIICgRHYW5kEAMS",
            "CgoGTGVhZ3VlEAQSCAoEVGVhbRAFKiEKCkNoYW5nZVR5cGUSBwoDQWRkEAAS",
            "CgoGUmVkdWNlEAEqXAoMTW9uZXlBZGRUeXBlEhQKEE5vbmVNb25leUFkZFR5",
            "cGUQABIMCghSZWNoYXJnZRABEg0KCVVzZVRpY2tldBACEgwKCFN5c0F3YXJk",
            "EAMSCwoHR01Bd2FyZBAEKlIKD01vbmV5UmVkdWNlVHlwZRIXChNOb25lTW9u",
            "ZXlSZWR1Y2VUeXBlEAASCwoHQnV5U2hvcBABEg0KCUJ1eVRpY2tldBACEgoK",
            "BlJlYm9ybhADKi8KCUdvb2RzVHlwZRIJCgVFcXVpcBAAEggKBEl0ZW0QARIN",
            "CglNYXRlcmlhbHMQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::HHFramework.Proto.RoleType), typeof(global::HHFramework.Proto.OfflineType), typeof(global::HHFramework.Proto.LeaveSceneLineType), typeof(global::HHFramework.Proto.PlayerActionType), typeof(global::HHFramework.Proto.RoleBattleRetCode), typeof(global::HHFramework.Proto.ChatChannel), typeof(global::HHFramework.Proto.ChangeType), typeof(global::HHFramework.Proto.MoneyAddType), typeof(global::HHFramework.Proto.MoneyReduceType), typeof(global::HHFramework.Proto.GoodsType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HHFramework.Proto.Vector3), global::HHFramework.Proto.Vector3.Parser, new[]{ "X", "Y", "Z" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///角色类型
  /// </summary>
  public enum RoleType {
    /// <summary>
    ///玩家
    /// </summary>
    [pbr::OriginalName("Player")] Player = 0,
    /// <summary>
    ///怪
    /// </summary>
    [pbr::OriginalName("Monster")] Monster = 1,
  }

  /// <summary>
  ///玩家下线类型
  /// </summary>
  public enum OfflineType {
    /// <summary>
    ///服务器维护
    /// </summary>
    [pbr::OriginalName("ServerMaintain")] ServerMaintain = 0,
    /// <summary>
    ///顶下线
    /// </summary>
    [pbr::OriginalName("Replace")] Replace = 1,
  }

  /// <summary>
  ///离开场景线类型
  /// </summary>
  public enum LeaveSceneLineType {
    /// <summary>
    ///普通
    /// </summary>
    [pbr::OriginalName("Normal")] Normal = 0,
    /// <summary>
    ///死亡
    /// </summary>
    [pbr::OriginalName("Die")] Die = 1,
  }

  /// <summary>
  ///玩家操作类型
  /// </summary>
  public enum PlayerActionType {
    /// <summary>
    ///点击移动
    /// </summary>
    [pbr::OriginalName("ClickMove")] ClickMove = 0,
    /// <summary>
    ///服务器移动
    /// </summary>
    [pbr::OriginalName("ServerMove")] ServerMove = 1,
    /// <summary>
    ///摇杆移动
    /// </summary>
    [pbr::OriginalName("JoystickMove")] JoystickMove = 2,
    /// <summary>
    ///摇杆抬起
    /// </summary>
    [pbr::OriginalName("JoystickStop")] JoystickStop = 3,
  }

  public enum RoleBattleRetCode {
    [pbr::OriginalName("None")] None = 0,
    /// <summary>
    ///MP不足
    /// </summary>
    [pbr::OriginalName("MpDeficiency")] MpDeficiency = 1,
  }

  /// <summary>
  ///聊天频道
  /// </summary>
  public enum ChatChannel {
    /// <summary>
    ///系统
    /// </summary>
    [pbr::OriginalName("Sys")] Sys = 0,
    /// <summary>
    ///世界
    /// </summary>
    [pbr::OriginalName("World")] World = 1,
    /// <summary>
    ///好友
    /// </summary>
    [pbr::OriginalName("Friend")] Friend = 2,
    /// <summary>
    ///帮会
    /// </summary>
    [pbr::OriginalName("Gand")] Gand = 3,
    /// <summary>
    ///同盟
    /// </summary>
    [pbr::OriginalName("League")] League = 4,
    /// <summary>
    ///队伍
    /// </summary>
    [pbr::OriginalName("Team")] Team = 5,
  }

  /// <summary>
  ///更新方式
  /// </summary>
  public enum ChangeType {
    /// <summary>
    ///增加
    /// </summary>
    [pbr::OriginalName("Add")] Add = 0,
    /// <summary>
    ///减少
    /// </summary>
    [pbr::OriginalName("Reduce")] Reduce = 1,
  }

  /// <summary>
  ///元宝增加方式
  /// </summary>
  public enum MoneyAddType {
    [pbr::OriginalName("NoneMoneyAddType")] NoneMoneyAddType = 0,
    /// <summary>
    ///充值
    /// </summary>
    [pbr::OriginalName("Recharge")] Recharge = 1,
    /// <summary>
    ///元宝票
    /// </summary>
    [pbr::OriginalName("UseTicket")] UseTicket = 2,
    /// <summary>
    ///系统奖励
    /// </summary>
    [pbr::OriginalName("SysAward")] SysAward = 3,
    /// <summary>
    ///GM奖励或补偿
    /// </summary>
    [pbr::OriginalName("GMAward")] Gmaward = 4,
  }

  /// <summary>
  ///元宝减少方式
  /// </summary>
  public enum MoneyReduceType {
    [pbr::OriginalName("NoneMoneyReduceType")] NoneMoneyReduceType = 0,
    /// <summary>
    ///购买商城物品
    /// </summary>
    [pbr::OriginalName("BuyShop")] BuyShop = 1,
    /// <summary>
    ///兑换成元宝票
    /// </summary>
    [pbr::OriginalName("BuyTicket")] BuyTicket = 2,
    /// <summary>
    ///原地复活
    /// </summary>
    [pbr::OriginalName("Reborn")] Reborn = 3,
  }

  /// <summary>
  ///物品类型
  /// </summary>
  public enum GoodsType {
    /// <summary>
    ///装备
    /// </summary>
    [pbr::OriginalName("Equip")] Equip = 0,
    /// <summary>
    ///道具
    /// </summary>
    [pbr::OriginalName("Item")] Item = 1,
    /// <summary>
    ///材料
    /// </summary>
    [pbr::OriginalName("Materials")] Materials = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  ///Vector3
  /// </summary>
  public sealed partial class Vector3 : HHFramework.IProto, pb::IMessage<Vector3> {
    private static readonly pb::MessageParser<Vector3> _parser = new pb::MessageParser<Vector3>(() => new Vector3());
    public ushort ProtoId => ProtoIdDefine.Proto_Vector3;
    public string ProtoEnName => "Vector3";
    public ProtoCategory Category => ProtoCategory.None;
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Vector3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HHFramework.Proto.ProtoCommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3(Vector3 other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vector3 Clone() {
      return new Vector3(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Vector3);
    }

    public bool Equals(Vector3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    public void MergeFrom(Vector3 other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
